accounts/urls.py
# myblog/accounts/urls.py

from django.urls import path

from . import views


app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

booklist/urls.py
from django.contrib import admin
from django.urls import path, include

from my_booklist.views import *


urlpatterns = [
    path('', BookCreateView.as_view(), name='index'),
    #path('search/', BookSearch, name='search'),
    path('isbn/', isbn_search, name='isbn'),
    path('detail/<int:pk>/', DetailView.as_view(), name='detail'),
    path('detail/<int:pk>/rent/', RentNow, name='rent'),
    path('return/', ReturnBooksView.as_view(), name='return_view'),
    path('return/<int:pk>', ReturnNow, name='return_now'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')), #認証関連
    path('accounts/', include('accounts.urls')), #サインアップ
]

my_booklist/models.py
from django.db import models
from django.core.validators import RegexValidator, MinLengthValidator
from django.utils.timezone import now


class Book(models.Model):
    title = models.CharField(max_length=200)
    subtitle = models.CharField(max_length=200, blank=True, null=True)

    author1 = models.CharField(max_length=50)
    author2 = models.CharField(max_length=50, blank=True, null=True)
    author3 = models.CharField(max_length=50, blank=True, null=True)
    author4 = models.CharField(max_length=200, blank=True, null=True)

    add_date = models.DateTimeField(default=now)

    isbn_regex = RegexValidator(regex=r'^[0-9]+$')
    isbn = models.CharField(validators=[isbn_regex, MinLengthValidator(10)],
                            max_length=13, unique=True)

    NUMERICAL_CALCULATION = 'nc'
    SOLID_STATE_PHYSICS = 'ss'
    QUANTUM_FIELD_THEORY = 'qf'
    ELECTROMAGNETISM = 'em'
    ANALYTICAL_MECHANICS = 'am'
    PHYSICS = 'ph'
    STATISTICAL_MECHANICS = 'sm'
    QUANTUM_MECHANICS = 'qm'
    QUANTUM_OPTICS = 'qo'
    QUANTUM_INFORMATION = 'qi'
    QUANTUM_PHYSICS = 'qp'
    PROBABILITY_PROCESS = 'pp'
    MATHEMATICS = 'mt'
    OTHERS = 'ot'

    CATEGORY_CHOICES = (
        (QUANTUM_MECHANICS, '量子力学(qm)'),
        (QUANTUM_OPTICS, '量子光学(qo)'),
        (QUANTUM_INFORMATION, '量子情報(qi)'),
        (QUANTUM_PHYSICS, '量子物理学(qp)'),
        (QUANTUM_FIELD_THEORY, '場の量子論(qf)'),
        (SOLID_STATE_PHYSICS, '固体物理学・超伝導(ss)'),
        (STATISTICAL_MECHANICS, '統計力学(sm)'),
        (ELECTROMAGNETISM, '電磁気学(em)'),
        (ANALYTICAL_MECHANICS, '力学・解析力学(am)'),
        (PHYSICS, '物理学一般(ph)'),
        (PROBABILITY_PROCESS, '確率過程(pp)'),
        (NUMERICAL_CALCULATION, '計算機・数値計算(nc)'),
        (MATHEMATICS, '数学(mt)'),
        (OTHERS, 'その他(ot)')
    )
    category = models.CharField(
        max_length=2,
        choices=CATEGORY_CHOICES
    )

    rent_flag = models.BooleanField(
        default=False
    )
    rent_user = models.CharField(max_length=50, blank=True, null=True)
    rent_date = models.DateTimeField(default=now, blank=True, null=True)

    def __str__(self):
        return self.title

my_booklist/forms.py
from django.forms import ModelForm, TextInput
from .models import Book


class BookForm(ModelForm):

    class Meta:
        model = Book
        fields = ('isbn', 'title', 'subtitle', 'author1', 'author2', 'author3', 'author4', 'category')

        labels = {
            'isbn': 'ISBN',
            'title': '書名',
            'subtitle': '副題',
            'author1': '著者',
            'category': '分類',
        }

        widgets = {
            'title': TextInput(attrs={'size': 42}),
            'subtitle': TextInput(attrs={'size': 42}),
            'author1': TextInput(attrs={'size': 20}),
            'author2': TextInput(attrs={'size': 20}),
            'author3': TextInput(attrs={'size': 20}),
            'author4': TextInput(attrs={'size': 20}),
        }

my_booklist/views.py
from django.views.generic import CreateView, DetailView, TemplateView
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Book
from .forms import BookForm

import requests
import numpy as np
from datetime import datetime


def isbn_checker(ISBN):
    if ISBN[:-1].isdecimal():
        if ISBN[-1] == 'X':
            chk_dig = 10
        else:
            chk_dig = int(ISBN[-1])

        isbn = np.array(list(map(int, ISBN)))

        if len(isbn) == 10:
            return (11 - sum(np.linspace(10, 2, 9) * isbn[:-1]) % 11) % 11 == chk_dig
        elif len(isbn) == 13:
            return (10 - sum(np.array([1, 3] * 6) * isbn[:-1]) % 10) % 10 == chk_dig
        else:
            return False
    else:
        return False


@login_required
def isbn_search(request):
    isbn = request.POST.get('isbn')
    redirect_url = '/?'

    if isbn_checker(isbn):
        url = 'https://www.googleapis.com/books/v1/volumes?q=isbn:{}'.format(isbn)
        headers = {"content-type": "application/json"}
        req = requests.get(url, headers)
        data = req.json()

        query_list = ['isbn={}'.format(isbn)]

        if data['totalItems'] == 1:
            Info = data['items'][0]['volumeInfo']

            if 'title' in Info:
                query_list.append('title=' + Info['title'])

                if 'subtitle' in Info:
                    query_list.append('subtitle=' + Info['subtitle'])

            if 'authors' in Info:
                query_list.append('authors=' + '_'.join(Info['authors']))

            if len(query_list) > 1:
                redirect_url += '&'.join(query_list)
            else:
                redirect_url += 'error=true&{}'.format(query_list[0])
        else:
            redirect_url += 'error=true&{}'.format(query_list[0])
    else:
        redirect_url += 'error=true'

    return redirect(redirect_url)


class BookCreateView(LoginRequiredMixin, CreateView):
    login_url = '/accounts/login/'

    model = Book
    form_class = BookForm
    template_name = "my_booklist/table.html"
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['books'] = Book.objects.all().order_by('category')
        context['username'] = self.request.user.username
        context['rent_count'] = Book.objects.filter(rent_user=self.request.user.username).count()
        return context

    def get_initial(self):
        initial = super(BookCreateView, self).get_initial()
        get_request = self.request.GET

        if not get_request.get('error'):
            if get_request.get('isbn'):
                initial['isbn'] = get_request.get('isbn')

            if get_request.get('title'):
                initial['title'] = get_request.get('title')

                if get_request.get('subtitle'):
                    initial['subtitle'] = get_request.get('subtitle')

            if get_request.get('authors'):
                authors_list = get_request.get('authors').split("_")
                authors_num = len(authors_list)

                if authors_num < 5:
                    for i in range(len(authors_list)):
                        initial['author{}'.format(i+1)] = authors_list[i]

                else:
                    for i in range(3):
                        initial['author{}'.format(i+1)] = authors_list[i]

                    initial['author4'] = ', '.join(authors_list[3:])
        else:
            initial['isbn'] = 'error'

        return initial

    def form_valid(self, form):
        messages.success(self.request, '書籍を追加しました')
        return super(BookCreateView, self).form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, '書籍を追加できませんでした')
        return super(BookCreateView, self).form_valid(form)


class DetailView(LoginRequiredMixin, DetailView):
    login_url = '/accounts/login/'

    model = Book
    template_name = 'my_booklist/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['username'] = self.request.user.username
        return context

@login_required
def RentNow(request, pk):
    book = Book.objects.get(pk=pk)

    if (not book.rent_flag) and book.rent_user is None:
        book.rent_flag = True
        book.rent_user = request.user.username
        book.rent_date = datetime.now()

        book.save()

    return redirect('detail', pk=pk)


class ReturnBooksView(LoginRequiredMixin, TemplateView):
    login_url = '/accounts/login/'
    template_name = 'my_booklist/return_view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) # はじめに継承元のメソッドを呼び出す
        context['books'] = Book.objects.filter(rent_user=self.request.user.username)
        context['username'] = self.request.user.username

        return context


@login_required
def ReturnNow(request, pk):
    book = Book.objects.get(pk=pk)

    if book.rent_flag and book.rent_user == request.user.username:
        book.rent_flag = False
        book.rent_user = None
        book.rent_date = None
        book.save()

    return redirect(request.META['HTTP_REFERER'])

my_booklist/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="jp">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    <!-- 必要なメタタグ -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>

<body>
    <!-- ナビゲーションバー -->
    {% include 'navbar.html' %}

    {% block contents %}{% endblock %}

    <!-- Bootstrap JS -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    {% block scripts %}{% endblock %}
</body>

</html>

my_booklist/templates/navbar.html
<nav class="navbar navbar-expand-md navbar-dark" style="background-color: #4a59a7;">
    <a class="navbar-brand" href="/">AMOG BOOK LIST</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
         <ul class="nav navbar-nav">
             <li class="nav-item">
                 <a class="nav-link" href="{% url 'return_view' %}">ReturnBooks</a>
             </li>
             <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
             </li>
             <li class="nav-item">
                <a class="nav-link" href="{% url 'password_change' %}">PasswordChange</a>
             </li>
             <li class="nav-item">
                 <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
             </li>
         </ul>
    </div>
</nav>