accounts/urls.py
# myblog/accounts/urls.py

from django.urls import path

from . import views


app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

booklist/urls.py
from django.contrib import admin
from django.urls import path, include

from my_booklist.views import *


urlpatterns = [
    path('', BookCreateView.as_view(), name='index'),
    #path('search/', BookSearch, name='search'),
    path('isbn/', isbn_search, name='isbn'),
    path('detail/<int:pk>/', DetailView.as_view(), name='detail'),
    path('detail/<int:pk>/rent/', RentNow, name='rent'),
    path('return/', ReturnBooksView.as_view(), name='return_view'),
    path('return/<int:pk>', ReturnNow, name='return_now'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')), #認証関連
    path('accounts/', include('accounts.urls')), #サインアップ
]

my_booklist/models.py
from django.db import models
from django.core.validators import RegexValidator, MinLengthValidator
from django.utils.timezone import now


class Book(models.Model):
    title = models.CharField(max_length=200)
    subtitle = models.CharField(max_length=200, blank=True, null=True)

    author1 = models.CharField(max_length=50)
    author2 = models.CharField(max_length=50, blank=True, null=True)
    author3 = models.CharField(max_length=50, blank=True, null=True)
    author4 = models.CharField(max_length=200, blank=True, null=True)

    add_date = models.DateTimeField(default=now)

    isbn_regex = RegexValidator(regex=r'^[0-9]+$')
    isbn = models.CharField(validators=[isbn_regex, MinLengthValidator(10)],
                            max_length=13, unique=True)

    NUMERICAL_CALCULATION = 'nc'
    SOLID_STATE_PHYSICS = 'ss'
    QUANTUM_FIELD_THEORY = 'qf'
    ELECTROMAGNETISM = 'em'
    ANALYTICAL_MECHANICS = 'am'
    PHYSICS = 'ph'
    STATISTICAL_MECHANICS = 'sm'
    QUANTUM_MECHANICS = 'qm'
    QUANTUM_OPTICS = 'qo'
    QUANTUM_INFORMATION = 'qi'
    QUANTUM_PHYSICS = 'qp'
    PROBABILITY_PROCESS = 'pp'
    MATHEMATICS = 'mt'
    OTHERS = 'ot'

    CATEGORY_CHOICES = (
        (QUANTUM_MECHANICS, '量子力学(qm)'),
        (QUANTUM_OPTICS, '量子光学(qo)'),
        (QUANTUM_INFORMATION, '量子情報(qi)'),
        (QUANTUM_PHYSICS, '量子物理学(qp)'),
        (QUANTUM_FIELD_THEORY, '場の量子論(qf)'),
        (SOLID_STATE_PHYSICS, '固体物理学・超伝導(ss)'),
        (STATISTICAL_MECHANICS, '統計力学(sm)'),
        (ELECTROMAGNETISM, '電磁気学(em)'),
        (ANALYTICAL_MECHANICS, '力学・解析力学(am)'),
        (PHYSICS, '物理学一般(ph)'),
        (PROBABILITY_PROCESS, '確率過程(pp)'),
        (NUMERICAL_CALCULATION, '計算機・数値計算(nc)'),
        (MATHEMATICS, '数学(mt)'),
        (OTHERS, 'その他(ot)')
    )
    category = models.CharField(
        max_length=2,
        choices=CATEGORY_CHOICES
    )

    rent_flag = models.BooleanField(
        default=False
    )
    rent_user = models.CharField(max_length=50, blank=True, null=True)
    rent_date = models.DateTimeField(default=now, blank=True, null=True)

    def __str__(self):
        return self.title

my_booklist/forms.py
from django.forms import ModelForm, TextInput
from .models import Book


class BookForm(ModelForm):

    class Meta:
        model = Book
        fields = ('isbn', 'title', 'subtitle', 'author1', 'author2', 'author3', 'author4', 'category')

        labels = {
            'isbn': 'ISBN',
            'title': '書名',
            'subtitle': '副題',
            'author1': '著者',
            'category': '分類',
        }

        widgets = {
            'title': TextInput(attrs={'size': 42}),
            'subtitle': TextInput(attrs={'size': 42}),
            'author1': TextInput(attrs={'size': 20}),
            'author2': TextInput(attrs={'size': 20}),
            'author3': TextInput(attrs={'size': 20}),
            'author4': TextInput(attrs={'size': 20}),
        }

my_booklist/views.py
from django.views.generic import CreateView, DetailView, TemplateView
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Book
from .forms import BookForm

import requests
import numpy as np
from datetime import datetime


def isbn_checker(ISBN):
    if ISBN[:-1].isdecimal():
        if ISBN[-1] == 'X':
            chk_dig = 10
        else:
            chk_dig = int(ISBN[-1])

        isbn = np.array(list(map(int, ISBN)))

        if len(isbn) == 10:
            return (11 - sum(np.linspace(10, 2, 9) * isbn[:-1]) % 11) % 11 == chk_dig
        elif len(isbn) == 13:
            return (10 - sum(np.array([1, 3] * 6) * isbn[:-1]) % 10) % 10 == chk_dig
        else:
            return False
    else:
        return False


@login_required
def isbn_search(request):
    isbn = request.POST.get('isbn')
    redirect_url = '/?'

    if isbn_checker(isbn):
        url = 'https://www.googleapis.com/books/v1/volumes?q=isbn:{}'.format(isbn)
        headers = {"content-type": "application/json"}
        req = requests.get(url, headers)
        data = req.json()

        query_list = ['isbn={}'.format(isbn)]

        if data['totalItems'] == 1:
            Info = data['items'][0]['volumeInfo']

            if 'title' in Info:
                query_list.append('title=' + Info['title'])

                if 'subtitle' in Info:
                    query_list.append('subtitle=' + Info['subtitle'])

            if 'authors' in Info:
                query_list.append('authors=' + '_'.join(Info['authors']))

            if len(query_list) > 1:
                redirect_url += '&'.join(query_list)
            else:
                redirect_url += 'error=true&{}'.format(query_list[0])
        else:
            redirect_url += 'error=true&{}'.format(query_list[0])
    else:
        redirect_url += 'error=true'

    return redirect(redirect_url)


class BookCreateView(LoginRequiredMixin, CreateView):
    login_url = '/accounts/login/'

    model = Book
    form_class = BookForm
    template_name = "my_booklist/table.html"
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['books'] = Book.objects.all().order_by('category')
        context['username'] = self.request.user.username
        context['rent_count'] = Book.objects.filter(rent_user=self.request.user.username).count()
        return context

    def get_initial(self):
        initial = super(BookCreateView, self).get_initial()
        get_request = self.request.GET

        if not get_request.get('error'):
            if get_request.get('isbn'):
                initial['isbn'] = get_request.get('isbn')

            if get_request.get('title'):
                initial['title'] = get_request.get('title')

                if get_request.get('subtitle'):
                    initial['subtitle'] = get_request.get('subtitle')

            if get_request.get('authors'):
                authors_list = get_request.get('authors').split("_")
                authors_num = len(authors_list)

                if authors_num < 5:
                    for i in range(len(authors_list)):
                        initial['author{}'.format(i+1)] = authors_list[i]

                else:
                    for i in range(3):
                        initial['author{}'.format(i+1)] = authors_list[i]

                    initial['author4'] = ', '.join(authors_list[3:])
        else:
            initial['isbn'] = 'error'

        return initial

    def form_valid(self, form):
        messages.success(self.request, '書籍を追加しました')
        return super(BookCreateView, self).form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, '書籍を追加できませんでした')
        return super(BookCreateView, self).form_valid(form)


class DetailView(LoginRequiredMixin, DetailView):
    login_url = '/accounts/login/'

    model = Book
    template_name = 'my_booklist/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['username'] = self.request.user.username
        return context

@login_required
def RentNow(request, pk):
    book = Book.objects.get(pk=pk)

    if (not book.rent_flag) and book.rent_user is None:
        book.rent_flag = True
        book.rent_user = request.user.username
        book.rent_date = datetime.now()

        book.save()

    return redirect('detail', pk=pk)


class ReturnBooksView(LoginRequiredMixin, TemplateView):
    login_url = '/accounts/login/'
    template_name = 'my_booklist/return_view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) # はじめに継承元のメソッドを呼び出す
        context['books'] = Book.objects.filter(rent_user=self.request.user.username)
        context['username'] = self.request.user.username

        return context


@login_required
def ReturnNow(request, pk):
    book = Book.objects.get(pk=pk)

    if book.rent_flag and book.rent_user == request.user.username:
        book.rent_flag = False
        book.rent_user = None
        book.rent_date = None
        book.save()

    return redirect(request.META['HTTP_REFERER'])

my_booklist/templates/my_booklist/detail.html
{% extends "index.html" %}

{% block title %}{{ book.title }}{% endblock %}

{% block contents %}

    <div class="container">
        <div class="table-responsive">
        <h3>詳細</h3>
            <table class="table table-striped table-hover text-nowrap">
                <tbody>
                    <tr><th>書名</th><td>{{ book.title }}</td></tr>
                    <tr><th>副題</th><td>{% if book.subtitle %}{{ book.subtitle }}{% endif %}</td></tr>
                    <tr><th>著者1</th><td>{{ book.author1 }}</td></tr>
                    <tr><th>著者2</th><td>{% if book.author2 %}{{ book.author2 }}{% endif %}</td></tr>
                    <tr><th>著者3</th><td>{% if book.author3 %}{{ book.author3 }}{% endif %}</td></tr>
                    <tr><th>著者4</th><td>{% if book.author4 %}{{ book.author4 }}{% endif %}</td></tr>
                    <tr><th>分類</th><td>{{ book.get_category_display }}</td></tr>
                    <tr><th>ISBN</th><td>
                        {% if book.isbn %}
                            <a href="https://www.amazon.co.jp/gp/search/?field-isbn={{ book.isbn }}">
                                {{ book.isbn }}
                            </a>
                        {% endif %}
                    </td></tr>
                    <tr><th>登録日</th><td>{{ book.add_date }}</td></tr>
                </tbody>
            </table>
        </div>

        <div class="col">
        <h3>持出状況</h3>
        {% if book.rent_flag %}
            <ul class="list-group-flush">
                <li class="list-group-item">持出状況：<em class="text-danger">持出中</em></li>
                <li class="list-group-item">持出者：{{ book.rent_user }}</li>
                <li class="list-group-item">持出日：{{ book.rent_date }}</li>
                {% if book.rent_user == username %}
                    <li class="list-group-item">
                        <a class="btn btn-outline-danger" href="{% url 'return_now' book.pk %}">返却</a>
                    </li>
                {% endif %}
            </ul>
        {% else %}
            <ul class="list-group-flush">
                <li class="list-group-item">持出状況：<em class="text-success">持出可能</em></li>
                <li class="list-group-item">
                    <a class="btn btn-outline-success" href="{% url 'rent' book.pk %}">持ち出す</a>
                </li>
            </ul>
        {% endif %}
        </div>

        <div class="col">
            <a class="btn btn-primary btn-block" href="/" role="button">Back</a>
        </div>
    </div>

{% endblock %}

my_booklist/templates/my_booklist/return_view.html
{% extends "index.html" %}

{% block title %}Return Books{% endblock %}

{% block contents %}

    <div class="container">
        <div class="table-responsive">
        <h3>{{ username }}さんが持ち出し中の書籍一覧</h3>
            <table class="table table-striped table-hover text-nowrap">
                <thead class="thead-dark">
                <tr>
                    <th>書名</th>
                    <th>持出日</th>
                    <th>返却</th>
                </thead>
                <tbody>
                {% for book in books %}
                    <tr>
                        <td>{{ book.title }}</td>
                        <td>{{ book.rent_date }}</td>
                        <td><a class="btn btn-outline-danger" href="{% url 'return_now' book.pk %}">返却</a></td>
                    </tr>
                {% empty %}
                    <tr><td colspan="3">持ち出し中の書籍はありません</td></tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="col">
            <a class="btn btn-primary btn-block" href="/" role="button">Back</a>
        </div>
    </div>

{% endblock %}

my_booklist/templates/my_booklist/table.html
{% extends "index.html" %}

{% load static %}

{% block title %}AMOG Book List{% endblock %}

{% block scripts %}
    <!-- TableSorter JS -->
    <script type="text/javascript" src="{% static 'js/jquery.tablesorter.js' %}"></script>
    <script>
        $(document).ready(function(){
                $("#tablesorter").tablesorter();
        });
    </script>
{% endblock %}

{% block contents %}

    <div class="row justify-content-md-center">
        <div class="col-md-auto">
            <ul class="list-unstyled">
                <li class="lead">
                    {{ username }}さん こんにちは！　
                </li>
                {% if rent_count > 0 %}
                    <li class="lead">
                        現在 <a href="{% url 'return_view' %}">{{ rent_count }}</a> 冊 持ち出し中です
                    </li>
                {% endif %}
            </ul>

            <div class="table-responsive">
                <h3>書籍の追加</h3>
                {% if messages %}
                    {% for message in messages %}
                        <div {% if message.tags %} class="alert alert-{{ message.tags }}{% endif %}" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                <button type="button" class="btn btn-light" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                    ISBNで書籍情報を入力
                </button>

                <div class="collapse" id="collapseExample">
                    <table class="table table-sm text-nowrap">
                        <form action='{% url 'isbn' %}' method="POST" id="id_isbn">
                            {% csrf_token %}
                            <tbody>
                            <th><label>ISBN:</label></th>
                            <td>
                                <input type="text" name="isbn" maxlength="13">
                                <button type="submit" class="btn-info">Search</button>
                            </td>
                            </tbody>
                        </form>
                    </table>
                </div>

                <table class="table table-sm text-nowrap">
                    <form method="post" id="BookForm">
                        {% csrf_token %}
                        <tbody>
                        <tr>
                            <th>{{ form.title.label_tag }}</th>
                            <td>{{ form.title }}</td>
                        </tr>
                        <tr>
                            <th>{{ form.subtitle.label_tag }}</th>
                            <td>{{ form.subtitle }}</td>
                        </tr>
                        <tr>
                            <th rowspan="2">{{ form.author1.label_tag }}</th>
                            <td>
                                {{ form.author1 }}
                                {{ form.author2 }}
                            </td>
                        </tr>
                        <tr>
                            <td>
                                {{ form.author3 }}
                                {{ form.author4 }}
                            </td>
                        </tr>
                        <tr>
                            <th>{{ form.isbn.label_tag }}</th>
                            <td>
                                {{ form.isbn }}
                            </td>
                        </tr>
                        <tr>
                            <th>{{ form.category.label_tag }}</th>
                            <td>
                                {{ form.category }}
                                <button type="submit" class="btn-primary">Add book</button>
                                <a class="btn btn-light" href="/" role="button">Reset</a>
                            </td>
                        </tr>
                        </tbody>
                    </form>
                </table>
            </div>
        </div>

        <div class="col-md-auto">
            <h3>書籍リスト</h3>
            <ul>
                <li>書名をクリックで詳細表示・持出処理ができます</li>
                <li>表の見出しをクリックで並べ替えができます</li>
            </ul>
            <div class="table-responsive">
                <table class="table table-striped table-hover text-nowrap" id="tablesorter">
                    <thead class="thead-dark">
                    <tr>
                        <th>分類</th>
                        <th>書名</th>
                        <th>著者1</th>
                        <th>持出状況</th>
                    </thead>
                    <tbody>
                    {% for book in books %}
                        <tr>
                            <td>{{ book.category }}</td>
                            <td><a class="text-body" href="{% url 'detail' book.pk %}">{{ book.title }}</a></td>
                            <td>{{ book.author1 }}</td>
                            {% if book.rent_flag %}
                                <td><em class="text-danger">持出中</em></td>
                            {% else %}
                                <td></td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}